int8      signal_name_index      # A string uniquely identifying the signal
---
int32 status                # For digital signals: 1 or 0. For register signals: The register value expressed as an integer.If the value is -1, it means the signal does not exist