/**:
  ros__parameters:
    default_planning_pipeline: ompl
    planning_pipelines: [pilz, ompl]
    pilz:
      planning_plugin: pilz_industrial_motion_planner/CommandPlanner
      default_planner_config: PTP
      start_state_max_bounds_error: 0.1
    capabilities: >-
      pilz_industrial_motion_planner/MoveGroupSequenceAction
      pilz_industrial_motion_planner/MoveGroupSequenceService
    ompl:
      planning_plugin: ompl_interface/OMPLPlanner
      request_adapters:
          default_planner_request_adapters/AddTimeOptimalParameterization
          default_planner_request_adapters/FixWorkspaceBounds
          default_planner_request_adapters/FixStartStateBounds
          default_planner_request_adapters/FixStartStateCollision
          default_planner_request_adapters/FixStartStatePathConstraints
      start_state_max_bounds_error: 0.1
